### ISSUE TITLE
serverless is not defined

### ISSUE THREAD

**Issue by jimmyn** [adriencaccia/serverless-analyze-bundle-plugin#21]
Environment: darwin, node 20.11.1, framework 3.38.0 (local), plugin 7.2.3, SDK 4.5.1

When I run `serverless package --analyze myFunction` I get the follwing error: 

```
Error:
ReferenceError: serverless is not defined
    at ServerlessAnalyzeBundlePlugin.bundleVisualizer (/Users/dmitriy/Work/test/node_modules/serverless-analyze-bundle-plugin/dist/index.cjs:68:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async after:package:finalize (/Users/dmitriy/Work/test/node_modules/serverless-analyze-bundle-plugin/dist/index.cjs:117:9)
    at async PluginManager.runHooks (/Users/dmitriy/Work/test/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/dmitriy/Work/test/node_modules/serverless/lib/classes/plugin-manager.js:565:9)
    at async PluginManager.run (/Users/dmitriy/Work/test/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/dmitriy/Work/test/node_modules/serverless/lib/serverless.js:179:5)
    at async /Users/dmitriy/Work/test/node_modules/serverless/scripts/serverless.js:819:9
```

**Comment by adriencaccia** [comment]
https://github.com/adriencaccia/serverless-analyze-bundle-plugin/releases/tag/v2.0.2 is now released and should fix the error
